UploadScore:
  - 'UploadScore/**'
GetScore:
  - 'GetScore/**'
BetaRegistration:
  - 'BetaRegistration/**'
CreateUser:
  - 'CreateUser/**'
AuthenticateUser:
  - 'AuthenticateUser/**'
GetUserData:
  - 'GetUserData/**'