UploadScore:
  - 'UploadScore/**'
GetScore:
  - 'GetScore/**'
CreateUser:
  - 'CreateUser/**'
AuthenticateUser:
  - 'AuthenticateUser/**'
GetUserData:
  - 'GetUserData/**'
GetPersonName:
  - 'GetPersonName/**'
InternalData:
  - 'InternalData/**'
ExternalData:
  - 'ExternalData/**'
UpdateUser:
  - 'UpdateUser/**'
RecoverPassword:
  - 'RecoverPassword/**'
GetComments:
  - 'GetComments/**'