UploadScore:
  - 'UploadScore/**'
GetScore:
  - 'GetScore/**'
CreateUser:
  - 'CreateUser/**'
AuthenticateUser:
  - 'AuthenticateUser/**'
GetUserData:
  - 'GetUserData/**'
GetPersonName:
  - 'GetPersonName/**'
InternalScoreData:
  - 'InternalScoreData/**'
ExternalScoreData:
  - 'ExternalScoreData/**'