version: 0.2
            
phases:

  install: 
    commands:
      - echo Installing dependencies...

  pre_build: 
    commands:
      - go test

  build:
    commands:
      - go build -o app

artifacts:
  files:
    - app
    - appspec.yml
    - buildspec.yml
    - config/*
    - codedeploy/*
    - cloudformation/*