name: Deploy to production environment

on:
  push:
    banches:
      -master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.18.1'
      - uses: dorny/paths-filter@v2.2.1
        id: filter
        with:
          filters: |
            UploadScore:
              - 'UploadScore/**/*'
            GetScores:
              - 'GetScores/**/*'
      - name: lint
        with:
          files: ${{ steps.filter.outputs.changed_files }}
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.26.0

          golangci-lint run 
      

