name: Deployment

on:
  push:
    branches:
      - master
jobs:
  changes:
    name: Files Verification
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.filter.outputs.locales }}
    steps:
      - name: Debug action
        uses: hmarr/debug-action@v2.0.1 
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2.2.1
        id: filter
        with:
          filters: |
            UploadScore:
              - 'UploadScore/**'
            GetScores:
              - 'GetScores/**'
  fuzz-test:
      needs: changes
      name: Unit testing
      runs-on: ubuntu-latest
      strategy:
        matrix:
          package: ${{ fromJSON(needs.changes.outputs.packages) }}
      steps:
        - uses: jidicula/go-fuzz-action@v1.1.0
          with:
            packages: './${{ matrix.package }}'
            fuzz-time: 30s
  deploy-serverless:
    name: Deploy lambda function(s)
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.1'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - uses: dorny/paths-filter@v2.2.1
        id: filter
        with:
          filters: .github/filters.yml
      - uses: blombard/lambda-monorepo@master
        with:
          lambda-functions: '${{ toJson(steps.filter.outputs) }}'
          zip-params: 'main'
      