name: Deploy to production environment

on:
  push:
    banches:
      -master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          stable: 'false'
          go-version: '1.18.1'
      - uses: dorny/paths-filter@v2.2.1
        id: filter
        with:
          filters: |
            UploadScore:
              - 'UploadScore/**/*'
            GetScores:
              - 'GetScores/**/*'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: ${{ steps.filter.outputs.changed_files }}