name: Deployment

on:
  push:
    branches:
      - master
jobs:
  unit-testing:
    name: Unit testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [UploadScore,GetScore]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.1'
      - name: Initialize go module
        working-directory: ${{strategy.matrix.package}}
        run: |
          go mod init testing_module
          go mod tidy
          go test ./... -coverprofile coverage.out -covermode count
          go tool cover -func coverage.out
        # run: |
        #   go mod init testing_module
        #   go mod tidy
        #   go test -v -cover ./...
      - name: Quality Gate - Test coverage shall be above threshold
        env:
            TESTCOVERAGE_THRESHOLD: 20
        run: |
            echo "Quality Gate: checking test coverage is above threshold ..."
            echo "Threshold             : $TESTCOVERAGE_THRESHOLD %"
            totalCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
            echo "Current test coverage : $totalCoverage %"
            if (( $(echo "$totalCoverage $TESTCOVERAGE_THRESHOLD" | awk '{print ($1 > $2)}') )); then
                echo "OK"
            else
                echo "Current test coverage is below threshold. Please add more unit tests or adjust threshold to a lower value."
                echo "Failed"
                exit 1
            fi  
  deploy-serverless:
    name: Deploy lambda function(s)
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.1'
      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ secrets.AWS_REGION }}
      - uses: dorny/paths-filter@v2.2.1
        id: filter
        with:
          filters: |
            UploadScore:
              - 'UploadScore/**'
            GetScores:
              - 'GetScores/**'
      - uses: blombard/lambda-monorepo@master
        with:
          lambda-functions: '${{ toJson(steps.filter.outputs) }}'
          zip-params: 'main'
      