name: Deployment

on:
  push:
    branches:
      - master
jobs:
  lint-verirication:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Lint Code Base
        uses: github/super-linter@v4.9.5
        env:
          FILTER_REGEX_EXCLUDE: .*.sh
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  deploy-serverless:
    needs: lint-verirication
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.1'
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - uses: dorny/paths-filter@v2.2.1
        id: filter
        with:
          filters: .github/filters.yml
      - uses: blombard/lambda-monorepo@master
        with:
          lambda-functions: '${{ toJson(steps.filter.outputs) }}'
          zip-params: 'main'
      